export const REGISTER_SELLER_REQUEST = 'REGISTER_SELLER_REQUEST'
export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS'
export const REGISTER_SELLER_FAIL = 'REGISTER_SELLER_FAIL'
export const NEW_SELLER_RESET= 'NEW_SELLER_RESET'

export const LOAD_SELLER_REQUEST = 'LOAD_SELLER_REQUEST'
export const LOAD_SELLER_SUCCESS = 'LOAD_SELLER_SUCCESS'
export const LOAD_SELLER_FAIL = 'LOAD_SELLER_FAIL'


export const ALL_SELLER_REQUEST = 'ALL_SELLER_REQUEST'
export const ALL_SELLER_SUCCESS = 'ALL_SELLER_SUCCESS'
export const ALL_SELLER_FAIL = 'ALL_SELLER_FAIL'

export const  DELETE_SELLER_REQUEST = ' DELETE_SELLER_REQUEST'
export const  DELETE_SELLER_SUCCESS = 'DELETE_SELLER_SUCCESS'
export const  DELETE_SELLER_FAIL = ' DELETE_SELLER_FAIL'
export const DELETE_SELLER_RESET = 'DELETE_SELLER_RESET'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'